import json, re, textwrap, os, unicodedata

categories = [
    {
      "id": "beaute-soins",
      "name_fr": "Beauté & Soins",
      "name_en": "Beauty & Care",
      "icon": "💄",
      "gradient_from": "#831843",
      "gradient_to": "#9f1239",
      "niches": [
        ("maquillage","Maquillage","Makeup"),
        ("soins-visage","Soins visage","Skincare"),
        ("soins-corps","Soins corps","Body Care"),
        ("parfums","Parfums","Perfumes"),
        ("soins-cheveux","Soins cheveux","Hair Care"),
        ("manucure-ongles","Manucure & ongles","Nails"),
        ("spa-bien-etre","Spa & bien-être","Spa & Wellness"),
        ("epilation-rasage","Épilation & rasage","Hair Removal & Shaving"),
        ("solaires-autobronzants","Solaires & autobronzants","Sun & Self-Tanning"),
        ("cosmetiques-bio-naturels","Cosmétiques bio & naturels","Natural Cosmetics"),
        ("hygiene-dentaire","Hygiène dentaire","Dental Hygiene"),
        ("soins-des-yeux","Soins des yeux","Eye Care"),
      ]
    },
    {
      "id": "mode-accessoires",
      "name_fr": "Mode & Accessoires",
      "name_en": "Fashion & Accessories",
      "icon": "👗",
      "gradient_from": "#4c1d95",
      "gradient_to": "#5b21b6",
      "niches": [
        ("vetements-femme","Vêtements femme","Women's Clothing"),
        ("chaussures","Chaussures","Shoes"),
        ("sacs-maroquinerie","Sacs & maroquinerie","Bags & Leather Goods"),
        ("bijoux-montres","Bijoux & montres","Jewellery & Watches"),
        ("lingerie","Lingerie","Lingerie"),
        ("sport-activewear","Sport & activewear","Sport & Activewear"),
        ("mode-grande-taille","Mode grande taille","Plus Size Fashion"),
        ("accessoires","Accessoires","Accessories"),
        ("maternite","Maternité","Maternity"),
        ("mode-enfant","Mode enfant","Kids Fashion"),
      ]
    },
    {
      "id": "maison-deco",
      "name_fr": "Maison & Déco",
      "name_en": "Home & Decor",
      "icon": "🏠",
      "gradient_from": "#78350f",
      "gradient_to": "#92400e",
      "niches": [
        ("literie-linge-de-lit","Literie & linge de lit","Bedding & Linen"),
        ("decoration-interieure","Décoration intérieure","Interior Decor"),
        ("meubles","Meubles","Furniture"),
        ("cuisine-arts-de-la-table","Cuisine & arts de la table","Kitchen & Tableware"),
        ("rangement-organisation","Rangement & organisation","Storage & Organisation"),
        ("luminaires","Luminaires","Lighting"),
        ("textiles","Textiles (rideaux, tapis)","Textiles"),
        ("salle-de-bain","Salle de bain","Bathroom"),
        ("bougies-parfums-interieur","Bougies & parfums d'intérieur","Candles & Home Fragrance"),
        ("papier-peint-peinture","Papier peint & peinture","Wallpaper & Paint"),
      ]
    },
    {
      "id": "cuisine-gastronomie",
      "name_fr": "Cuisine & Gastronomie",
      "name_en": "Food & Gastronomy",
      "icon": "🍽️",
      "gradient_from": "#7c2d12",
      "gradient_to": "#9a3412",
      "niches": [
        ("electromenager-cuisine","Électroménager cuisine","Kitchen Appliances"),
        ("ustensiles-accessoires","Ustensiles & accessoires","Utensils & Accessories"),
        ("epicerie-fine-terroir","Épicerie fine & terroir","Fine Food & Local Produce"),
        ("the-cafe-infusions","Thé, café & infusions","Tea, Coffee & Herbal Drinks"),
        ("vins-spiritueux","Vins & spiritueux","Wine & Spirits"),
        ("alimentation-bio","Alimentation bio","Organic Food"),
        ("epices-condiments","Épices & condiments","Spices & Condiments"),
        ("chocolat-confiserie","Chocolat & confiserie","Chocolate & Confectionery"),
        ("livres-de-cuisine","Livres de cuisine","Cookbooks"),
        ("meal-prep-lunch-box","Meal prep & lunch box","Meal Prep & Lunch Box"),
      ]
    },
    {
      "id": "sante-bien-etre",
      "name_fr": "Santé & Bien-être",
      "name_en": "Health & Wellness",
      "icon": "🌿",
      "gradient_from": "#134e4a",
      "gradient_to": "#115e59",
      "niches": [
        ("complements-alimentaires","Compléments alimentaires","Dietary Supplements"),
        ("vitamines-mineraux","Vitamines & minéraux","Vitamins & Minerals"),
        ("phytotherapie-aromatherapie","Phytothérapie & aromathérapie","Herbal & Aromatherapy"),
        ("medecines-douces","Médecines douces","Alternative Medicine"),
        ("yoga-meditation","Yoga & méditation","Yoga & Meditation"),
        ("sante-feminine","Santé féminine","Women's Health"),
        ("sante-intestinale","Santé intestinale","Gut Health"),
        ("sommeil-relaxation","Sommeil & relaxation","Sleep & Relaxation"),
        ("minceur-detox","Minceur & détox","Weight Loss & Detox"),
        ("hygiene-naturelle","Hygiène naturelle","Natural Hygiene"),
      ]
    },
    {
      "id": "sport-fitness",
      "name_fr": "Sport & Fitness",
      "name_en": "Sport & Fitness",
      "icon": "🏋️",
      "gradient_from": "#14532d",
      "gradient_to": "#166534",
      "niches": [
        ("equipement-fitness-maison","Équipement fitness maison","Home Fitness Equipment"),
        ("vetements-sport","Vêtements sport","Sportswear"),
        ("chaussures-sport","Chaussures sport","Sports Shoes"),
        ("nutrition-sportive","Nutrition sportive","Sports Nutrition"),
        ("running-cardio","Running & cardio","Running & Cardio"),
        ("yoga-pilates","Yoga & pilates","Yoga & Pilates"),
        ("sports-de-raquette","Sports de raquette","Racket Sports"),
        ("sports-d-hiver","Sports d'hiver","Winter Sports"),
        ("randonnee-outdoor","Randonnée & outdoor","Hiking & Outdoor"),
        ("natation-aquatique","Natation & aquatique","Swimming & Water Sports"),
      ]
    },
    {
      "id": "enfants-famille",
      "name_fr": "Enfants & Famille",
      "name_en": "Kids & Family",
      "icon": "👶",
      "gradient_from": "#0c4a6e",
      "gradient_to": "#075985",
      "niches": [
        ("puericulture-bebe","Puériculture & bébé","Baby Care"),
        ("jouets-jeux","Jouets & jeux","Toys & Games"),
        ("vetements-enfant","Vêtements enfant","Kids Clothing"),
        ("livres-education","Livres & éducation","Books & Education"),
        ("anniversaires-fetes","Anniversaires & fêtes","Birthdays & Parties"),
        ("securite-enfant","Sécurité enfant","Child Safety"),
        ("activites-creatives","Activités créatives","Creative Activities"),
        ("alimentation-bebe","Alimentation bébé","Baby Food"),
        ("mobilier-chambre-enfant","Mobilier chambre enfant","Kids Room Furniture"),
        ("fournitures-scolaires","Fournitures scolaires","School Supplies"),
      ]
    },
    {
      "id": "animaux",
      "name_fr": "Animaux",
      "name_en": "Pets",
      "icon": "🐾",
      "gradient_from": "#713f12",
      "gradient_to": "#854d0e",
      "niches": [
        ("alimentation-chien","Alimentation chien","Dog Food"),
        ("alimentation-chat","Alimentation chat","Cat Food"),
        ("accessoires-chien","Accessoires chien","Dog Accessories"),
        ("accessoires-chat","Accessoires chat","Cat Accessories"),
        ("soins-hygiene-animaux","Soins & hygiène animaux","Pet Care & Hygiene"),
        ("jouets-pour-animaux","Jouets pour animaux","Pet Toys"),
        ("aquariophilie","Aquariophilie","Aquariums"),
        ("rongeurs-lapins","Rongeurs & lapins","Rodents & Rabbits"),
        ("sante-animale","Santé animale","Animal Health"),
        ("elevage-reproduction","Élevage & reproduction","Breeding"),
      ]
    },
    {
      "id": "jardin-exterieur",
      "name_fr": "Jardin & Extérieur",
      "name_en": "Garden & Outdoors",
      "icon": "🌱",
      "gradient_from": "#1a2e05",
      "gradient_to": "#1e3a0f",
      "niches": [
        ("mobilier-de-jardin","Mobilier de jardin","Garden Furniture"),
        ("outillage-jardinage","Outillage jardinage","Gardening Tools"),
        ("plantes-fleurs","Plantes & fleurs","Plants & Flowers"),
        ("potager-semences","Potager & semences","Vegetable Garden & Seeds"),
        ("piscine-spa","Piscine & spa","Pool & Spa"),
        ("barbecue-plancha","Barbecue & plancha","BBQ & Plancha"),
        ("eclairage-exterieur","Éclairage extérieur","Outdoor Lighting"),
        ("abris-pergolas","Abris & pergolas","Shelters & Pergolas"),
        ("arrosage","Arrosage","Watering & Irrigation"),
        ("decoration-exterieure","Décoration extérieure","Outdoor Decor"),
      ]
    },
    {
      "id": "tech-high-tech",
      "name_fr": "Tech & High-Tech",
      "name_en": "Tech & Electronics",
      "icon": "📱",
      "gradient_from": "#1e3a5f",
      "gradient_to": "#1e3a8a",
      "niches": [
        ("smartphones-accessoires","Smartphones & accessoires","Smartphones & Accessories"),
        ("audio","Audio (casques, enceintes)","Audio (Headphones, Speakers)"),
        ("maison-connectee","Maison connectée","Smart Home"),
        ("wearables-montres","Wearables & montres","Wearables & Smartwatches"),
        ("photo-video","Photo & vidéo","Photo & Video"),
        ("tablettes-pc","Tablettes & PC","Tablets & PCs"),
        ("gaming","Gaming","Gaming"),
        ("accessoires-bureau","Accessoires bureau","Office Accessories"),
        ("chargeurs-batteries","Chargeurs & batteries","Chargers & Batteries"),
        ("impression-3d-domotique","Impression 3D & domotique","3D Printing & Home Automation"),
      ]
    },
    {
      "id": "voyage-loisirs",
      "name_fr": "Voyage & Loisirs",
      "name_en": "Travel & Leisure",
      "icon": "✈️",
      "gradient_from": "#164e63",
      "gradient_to": "#155e75",
      "niches": [
        ("bagages-valises","Bagages & valises","Luggage & Suitcases"),
        ("accessoires-voyage","Accessoires voyage","Travel Accessories"),
        ("livres-lecture","Livres & lecture","Books & Reading"),
        ("jeux-de-societe","Jeux de société","Board Games"),
        ("loisirs-creatifs","Loisirs créatifs","Creative Hobbies"),
        ("photographie","Photographie","Photography"),
        ("camping-bivouac","Camping & bivouac","Camping"),
        ("musique-instruments","Musique & instruments","Music & Instruments"),
        ("jeux-video","Jeux vidéo","Video Games"),
        ("puzzles-collections","Puzzles & collections","Puzzles & Collectibles"),
      ]
    },
    {
      "id": "senior",
      "name_fr": "Senior",
      "name_en": "Senior",
      "icon": "👴",
      "gradient_from": "#292524",
      "gradient_to": "#44403c",
      "niches": [
        ("mobilite-aide-marche","Mobilité & aide à la marche","Mobility Aids"),
        ("confort-bien-etre","Confort & bien-être","Comfort & Wellness"),
        ("sante-medicaments","Santé & médicaments","Health & Medicine"),
        ("loisirs-senior","Loisirs senior","Senior Leisure"),
        ("maison-adaptee","Maison adaptée","Adapted Home"),
        ("audition-optique","Audition & optique","Hearing & Vision"),
        ("numerique-senior","Numérique senior","Digital for Seniors"),
        ("voyage-senior","Voyage senior","Senior Travel"),
        ("garde-robe-confort","Garde-robe confort","Comfort Wardrobe"),
        ("jardinage-senior","Jardinage senior","Senior Gardening"),
      ]
    },
    {
      "id": "bricolage-diy",
      "name_fr": "Bricolage & DIY",
      "name_en": "DIY & Home Improvement",
      "icon": "🔧",
      "gradient_from": "#27272a",
      "gradient_to": "#3f3f46",
      "niches": [
        ("outillage-electroportatif","Outillage électroportatif","Power Tools"),
        ("peinture-enduits","Peinture & enduits","Paint & Coatings"),
        ("plomberie","Plomberie","Plumbing"),
        ("electricite","Électricité","Electrical"),
        ("quincaillerie","Quincaillerie","Hardware"),
        ("materiaux-construction","Matériaux & construction","Building Materials"),
        ("deco-diy-creatif","Déco DIY & créatif","Creative DIY Decor"),
        ("isolation-energie","Isolation & énergie","Insulation & Energy"),
        ("menuiserie","Menuiserie","Carpentry & Woodworking"),
        ("alarme-securite","Alarme & sécurité","Alarm & Security"),
      ]
    }
]

products_by_niche = {
"maquillage":[("rouge-a-levres","Rouge à lèvres","Lipstick"),("fond-de-teint","Fond de teint","Foundation"),("anticernes","Anticernes","Concealer"),("mascara","Mascara","Mascara"),("eyeliner","Eyeliner","Eyeliner"),("palette-fards","Palette de fards","Eyeshadow Palette"),("blush","Blush","Blush"),("poudre-libre","Poudre libre","Loose Powder"),("bronzer","Bronzer","Bronzer"),("highlighter","Illuminateur","Highlighter"),("fixateur-maquillage","Fixateur maquillage","Setting Spray"),("pinceaux-maquillage","Pinceaux maquillage","Makeup Brushes")],
"soins-visage":[("nettoyant-visage","Nettoyant visage","Facial Cleanser"),("eau-micellaire","Eau micellaire","Micellar Water"),("serum-vitamine-c","Sérum vitamine C","Vitamin C Serum"),("serum-acide-hyaluronique","Sérum acide hyaluronique","Hyaluronic Acid Serum"),("creme-hydratante","Crème hydratante","Moisturizer"),("creme-nuit","Crème de nuit","Night Cream"),("gommage-visage","Gommage visage","Face Scrub"),("masque-visage","Masque visage","Face Mask"),("tonique","Tonique","Toner"),("patchs-boutons","Patchs boutons","Pimple Patches"),("creme-anti-age","Crème anti-âge","Anti-Aging Cream"),("huile-visage","Huile visage","Face Oil")],
"soins-corps":[("gel-douche","Gel douche","Shower Gel"),("savon-solide","Savon solide","Bar Soap"),("lait-corps","Lait corps","Body Lotion"),("beurre-corporel","Beurre corporel","Body Butter"),("gommage-corps","Gommage corps","Body Scrub"),("huile-corporelle","Huile corporelle","Body Oil"),("deodorant","Déodorant","Deodorant"),("creme-mains","Crème mains","Hand Cream"),("creme-pieds","Crème pieds","Foot Cream"),("baume-corps","Baume corps","Body Balm"),("sel-de-bain","Sel de bain","Bath Salts"),("brosse-seche","Brosse sèche","Dry Brush")],
"parfums":[("parfum-femme","Parfum femme","Women's Perfume"),("parfum-homme","Parfum homme","Men's Perfume"),("eau-de-parfum","Eau de parfum","Eau de Parfum"),("eau-de-toilette","Eau de toilette","Eau de Toilette"),("brume-corporelle","Brume corporelle","Body Mist"),("coffret-parfum","Coffret parfum","Perfume Gift Set"),("parfum-solide","Parfum solide","Solid Perfume"),("bougie-parfumee","Bougie parfumée","Scented Candle"),("diffuseur-maison","Diffuseur maison","Home Diffuser"),("recharge-parfum","Recharge parfum","Perfume Refill")],
"soins-cheveux":[("shampoing","Shampoing","Shampoo"),("apres-shampoing","Après-shampoing","Conditioner"),("masque-capillaire","Masque capillaire","Hair Mask"),("huile-cheveux","Huile cheveux","Hair Oil"),("serum-pointes","Sérum pointes","Split End Serum"),("spray-thermoprotecteur","Spray thermoprotecteur","Heat Protectant Spray"),("mousse-coiffante","Mousse coiffante","Styling Mousse"),("laque","Laque","Hair Spray"),("shampoing-sec","Shampoing sec","Dry Shampoo"),("brosse-cheveux","Brosse cheveux","Hair Brush"),("fer-a-lisser","Fer à lisser","Hair Straightener"),("boucleur","Boucleur","Curling Iron")],
"manucure-ongles":[("vernis-a-ongles","Vernis à ongles","Nail Polish"),("base-ongles","Base ongles","Base Coat"),("top-coat","Top coat","Top Coat"),("faux-ongles","Faux ongles","Press-On Nails"),("gel-uv","Gel UV","UV Gel"),("lampe-uv","Lampe UV","UV Lamp"),("lime-a-ongles","Lime à ongles","Nail File"),("repousse-cuticules","Repousse-cuticules","Cuticle Pusher"),("huile-cuticules","Huile cuticules","Cuticle Oil"),("dissolvant","Dissolvant","Nail Polish Remover")],
"spa-bien-etre":[("peignoir","Peignoir","Bathrobe"),("chaussons-spa","Chaussons spa","Spa Slippers"),("rouleau-jade","Rouleau de jade","Jade Roller"),("gua-sha","Gua sha","Gua Sha"),("masque-yeux-gel","Masque yeux gel","Gel Eye Mask"),("oreiller-bain","Oreiller de bain","Bath Pillow"),("diffuseur-huiles-essentielles","Diffuseur d'huiles essentielles","Essential Oil Diffuser"),("huiles-essentielles","Huiles essentielles","Essential Oils"),("bougie-relaxante","Bougie relaxante","Relaxing Candle"),("tapis-acupression","Tapis d’acupression","Acupressure Mat")],
"epilation-rasage":[("rasoir-manuel","Rasoir manuel","Manual Razor"),("rasoir-electrique","Rasoir électrique","Electric Razor"),("epilateur-electrique","Épilateur électrique","Epilator"),("cire-epilation","Cire d'épilation","Hair Removal Wax"),("bandes-cire","Bandes de cire","Wax Strips"),("creme-depilatoire","Crème dépilatoire","Depilatory Cream"),("mousse-a-raser","Mousse à raser","Shaving Foam"),("huile-rasage","Huile de rasage","Shaving Oil"),("apres-rasage","Après-rasage","Aftershave"),("tondeuse-corps","Tondeuse corps","Body Trimmer")],
"solaires-autobronzants":[("creme-solaire-visage","Crème solaire visage","Face Sunscreen"),("creme-solaire-corps","Crème solaire corps","Body Sunscreen"),("spray-solaire","Spray solaire","Sunscreen Spray"),("stick-solaire","Stick solaire","Sun Stick"),("apres-soleil","Après-soleil","After Sun Lotion"),("autobronzant-mousse","Autobronzant mousse","Self-Tanning Mousse"),("autobronzant-gouttes","Autobronzant gouttes","Tanning Drops"),("gant-applicateur","Gant applicateur","Application Mitt"),("brume-protectrice-cheveux","Brume protectrice cheveux","Hair Sun Mist"),("baume-levres-spf","Baume lèvres SPF","SPF Lip Balm")],
"cosmetiques-bio-naturels":[("savon-bio","Savon bio","Organic Soap"),("deodorant-naturel","Déodorant naturel","Natural Deodorant"),("baume-levres-bio","Baume lèvres bio","Organic Lip Balm"),("creme-bio","Crème bio","Organic Cream"),("huile-argan","Huile d’argan","Argan Oil"),("aloe-vera-gel","Gel aloe vera","Aloe Vera Gel"),("shampoing-solide","Shampoing solide","Solid Shampoo"),("dentifrice-naturel","Dentifrice naturel","Natural Toothpaste"),("maquillage-mineral","Maquillage minéral","Mineral Makeup"),("hydrolat","Hydrolat","Floral Water")],
"hygiene-dentaire":[("brosse-a-dents-manuelle","Brosse à dents manuelle","Manual Toothbrush"),("brosse-a-dents-electrique","Brosse à dents électrique","Electric Toothbrush"),("brossettes-interdentaires","Brossettes interdentaires","Interdental Brushes"),("fil-dentaire","Fil dentaire","Dental Floss"),("jet-dentaire","Jet dentaire","Water Flosser"),("dentifrice-blancheur","Dentifrice blancheur","Whitening Toothpaste"),("dentifrice-sensibilite","Dentifrice sensibilité","Sensitive Toothpaste"),("gratte-langue","Gratte-langue","Tongue Scraper"),("bain-de-bouche","Bain de bouche","Mouthwash"),("kit-blanchiment","Kit blanchiment","Teeth Whitening Kit")],
"soins-des-yeux":[("creme-contour-yeux","Crème contour des yeux","Eye Cream"),("serum-cils","Sérum cils","Lash Serum"),("gouttes-oculaires","Gouttes oculaires","Eye Drops"),("masque-sommeil","Masque de sommeil","Sleep Mask"),("patchs-yeux","Patchs yeux","Eye Patches"),("lunettes-lumiere-bleue","Lunettes lumière bleue","Blue Light Glasses"),("compresses-yeux","Compresses yeux","Eye Compress"),("dequillant-yeux","Démaquillant yeux","Eye Makeup Remover")],
"vetements-femme":[("robe","Robe","Dress"),("jean-femme","Jean femme","Women's Jeans"),("blazer","Blazer","Blazer"),("pull","Pull","Sweater"),("t-shirt-femme","T-shirt femme","Women's T-Shirt"),("chemisier","Chemisier","Blouse"),("jupe","Jupe","Skirt"),("manteau","Manteau","Coat"),("pantalon","Pantalon","Trousers"),("combinaison","Combinaison","Jumpsuit")],
"chaussures":[("baskets","Baskets","Sneakers"),("bottes","Bottes","Boots"),("sandales","Sandales","Sandals"),("escarpins","Escarpins","Heels"),("mocassins","Mocassins","Loafers"),("chaussons","Chaussons","Slippers"),("chaussures-ville","Chaussures de ville","Dress Shoes"),("sneakers-blanches","Sneakers blanches","White Sneakers"),("bottines","Bottines","Ankle Boots"),("sabots","Sabots","Clogs")],
"sacs-maroquinerie":[("sac-a-main","Sac à main","Handbag"),("sac-bandouliere","Sac bandoulière","Crossbody Bag"),("sac-cabas","Sac cabas","Tote Bag"),("sac-a-dos-ville","Sac à dos ville","City Backpack"),("portefeuille","Portefeuille","Wallet"),("porte-cartes","Porte-cartes","Card Holder"),("ceinture-cuir","Ceinture cuir","Leather Belt"),("trousse-toilette","Trousse de toilette","Toiletry Bag"),("sac-voyage","Sac de voyage","Travel Bag"),("pochette-soiree","Pochette soirée","Clutch Bag")],
"bijoux-montres":[("collier","Collier","Necklace"),("bracelet","Bracelet","Bracelet"),("boucles-doreilles","Boucles d’oreilles","Earrings"),("bague","Bague","Ring"),("montre-analogique","Montre analogique","Analog Watch"),("montre-connectee-mode","Montre connectée mode","Fashion Smartwatch"),("chaine-cheville","Chaîne de cheville","Anklet"),("broche","Broche","Brooch"),("coffret-bijoux","Coffret bijoux","Jewelry Set"),("boite-a-bijoux","Boîte à bijoux","Jewelry Box")],
"lingerie":[("soutien-gorge","Soutien-gorge","Bra"),("culotte","Culotte","Panties"),("body","Body","Bodysuit"),("nuisette","Nuisette","Nightgown"),("pyjama","Pyjama","Pajamas"),("brassiere","Brassière","Bralette"),("bas","Bas","Stockings"),("collants","Collants","Tights")],
"sport-activewear":[("legging-sport","Legging sport","Sports Leggings"),("brassiere-sport","Brassière sport","Sports Bra"),("short-sport","Short sport","Sports Shorts"),("veste-running","Veste running","Running Jacket"),("t-shirt-technique","T-shirt technique","Performance T-Shirt"),("sweat-zippe","Sweat zippé","Zip Hoodie"),("jogging","Jogging","Joggers"),("coupe-vent","Coupe-vent","Windbreaker")],
"mode-grande-taille":[("robe-grande-taille","Robe grande taille","Plus Size Dress"),("jean-grande-taille","Jean grande taille","Plus Size Jeans"),("tunique-grande-taille","Tunique grande taille","Plus Size Tunic"),("legging-grande-taille","Legging grande taille","Plus Size Leggings"),("manteau-grande-taille","Manteau grande taille","Plus Size Coat"),("blouse-grande-taille","Blouse grande taille","Plus Size Blouse"),("maillot-grande-taille","Maillot grande taille","Plus Size Swimsuit"),("lingerie-grande-taille","Lingerie grande taille","Plus Size Lingerie")],
"accessoires":[("lunettes-de-soleil","Lunettes de soleil","Sunglasses"),("echarpe","Écharpe","Scarf"),("bonnet","Bonnet","Beanie"),("casquette","Casquette","Cap"),("gants","Gants","Gloves"),("parapluie","Parapluie","Umbrella"),("barrette-cheveux","Barrette cheveux","Hair Clip"),("foulard","Foulard","Silk Scarf"),("ceinture","Ceinture","Belt"),("porte-clefs","Porte-clés","Keychain")],
"maternite":[("legging-maternite","Legging maternité","Maternity Leggings"),("robe-maternite","Robe maternité","Maternity Dress"),("jean-maternite","Jean maternité","Maternity Jeans"),("soutien-gorge-allaitement","Soutien-gorge allaitement","Nursing Bra"),("coussin-allaitement","Coussin d’allaitement","Nursing Pillow"),("ceinture-grossesse","Ceinture de grossesse","Pregnancy Support Belt"),("pyjama-maternite","Pyjama maternité","Maternity Pajamas"),("tire-lait","Tire-lait","Breast Pump")],
"mode-enfant":[("t-shirt-enfant","T-shirt enfant","Kids T-Shirt"),("pantalon-enfant","Pantalon enfant","Kids Trousers"),("pyjama-enfant","Pyjama enfant","Kids Pajamas"),("baskets-enfant","Baskets enfant","Kids Sneakers"),("manteau-enfant","Manteau enfant","Kids Coat"),("robe-enfant","Robe enfant","Kids Dress"),("bonnet-enfant","Bonnet enfant","Kids Beanie"),("cartable-mode","Cartable","School Backpack")],
"literie-linge-de-lit":[("matelas","Matelas","Mattress"),("surmatelas","Surmatelas","Mattress Topper"),("oreiller","Oreiller","Pillow"),("couette","Couette","Duvet"),("parure-de-lit","Parure de lit","Bedding Set"),("drap-housse","Drap-housse","Fitted Sheet"),("taie-doreiller","Taie d’oreiller","Pillowcase"),("couverture","Couverture","Blanket"),("protege-matelas","Protège-matelas","Mattress Protector"),("plaid","Plaid","Throw Blanket")],
"decoration-interieure":[("miroir","Miroir","Mirror"),("cadre-photo","Cadre photo","Photo Frame"),("affiche-deco","Affiche déco","Decor Poster"),("vase","Vase","Vase"),("statuette","Statuette","Figurine"),("horloge-murale","Horloge murale","Wall Clock"),("plante-artificielle","Plante artificielle","Artificial Plant"),("cache-pot","Cache-pot","Plant Pot Cover"),("etagere-deco","Étagère déco","Decor Shelf"),("panier-deco","Panier déco","Decor Basket")],
"meubles":[("chaise","Chaise","Chair"),("table-a-manger","Table à manger","Dining Table"),("canape","Canapé","Sofa"),("fauteuil","Fauteuil","Armchair"),("bureau","Bureau","Desk"),("table-basse","Table basse","Coffee Table"),("etagere","Étagère","Shelf"),("commode","Commode","Chest of Drawers"),("lit","Lit","Bed Frame"),("tabouret","Tabouret","Stool")],
"cuisine-arts-de-la-table":[("assiette","Assiette","Plate"),("bol","Bol","Bowl"),("verre","Verre","Glass"),("mug","Mug","Mug"),("poele","Poêle","Frying Pan"),("casserole","Casserole","Saucepan"),("plat-four","Plat à four","Baking Dish"),("service-couverts","Service de couverts","Cutlery Set"),("planche-decouper","Planche à découper","Cutting Board"),("carafe","Carafe","Carafe")],
"rangement-organisation":[("boite-rangement","Boîte de rangement","Storage Box"),("etagere-modulable","Étagère modulable","Modular Shelf"),("panier-rangement","Panier rangement","Storage Basket"),("organiseur-tiroir","Organiseur tiroir","Drawer Organizer"),("porte-chaussures","Porte-chaussures","Shoe Rack"),("housse-vetements","Housse vêtements","Garment Bag"),("boite-chaussures","Boîte chaussures","Shoe Box"),("patere","Patère","Coat Hook"),("commode-rangement","Commode rangement","Storage Dresser"),("range-cables","Range-câbles","Cable Organizer")],
"luminaires":[("lampe-de-bureau","Lampe de bureau","Desk Lamp"),("suspension","Suspension","Pendant Light"),("applique-murale","Applique murale","Wall Light"),("lampadaire","Lampadaire","Floor Lamp"),("veilleuse","Veilleuse","Night Light"),("guirlande-lumineuse","Guirlande lumineuse","Fairy Lights"),("lampe-chevet","Lampe de chevet","Bedside Lamp"),("plafonnier","Plafonnier","Ceiling Light")],
"textiles":[("rideaux","Rideaux","Curtains"),("voilage","Voilage","Sheer Curtains"),("tapis","Tapis","Rug"),("housse-coussin","Housse de coussin","Cushion Cover"),("coussin","Coussin","Cushion"),("nappe","Nappe","Tablecloth"),("serviettes-table","Serviettes de table","Napkins"),("linge-maison","Linge de maison","Home Linen")],
"salle-de-bain":[("serviette-bain","Serviette de bain","Bath Towel"),("tapis-bain","Tapis de bain","Bath Mat"),("rideau-douche","Rideau de douche","Shower Curtain"),("distributeur-savon","Distributeur de savon","Soap Dispenser"),("etagere-douche","Étagère douche","Shower Caddy"),("miroir-salle-de-bain","Miroir salle de bain","Bathroom Mirror"),("porte-brosses","Porte-brosses","Toothbrush Holder"),("panier-linge","Panier à linge","Laundry Basket")],
"bougies-parfums-interieur":[("bougie-parfumee","Bougie parfumée","Scented Candle"),("diffuseur-batons","Diffuseur à bâtons","Reed Diffuser"),("spray-ambiance","Spray d’ambiance","Room Spray"),("fondants-parfumes","Fondants parfumés","Wax Melts"),("brule-parfum","Brûle-parfum","Wax Burner"),("encens","Encens","Incense"),("porte-encens","Porte-encens","Incense Holder"),("desodorisant-maison","Désodorisant maison","Home Freshener")],
"papier-peint-peinture":[("papier-peint","Papier peint","Wallpaper"),("peinture-murale","Peinture murale","Wall Paint"),("peinture-meuble","Peinture meuble","Furniture Paint"),("rouleau-peinture","Rouleau peinture","Paint Roller"),("pinceau-peinture","Pinceau peinture","Paint Brush"),("ruban-masquage","Ruban de masquage","Masking Tape"),("sous-couche","Sous-couche","Primer"),("nuancier","Nuancier","Color Chart")],
"electromenager-cuisine":[("airfryer","Airfryer","Air Fryer"),("blender","Blender","Blender"),("robot-patissier","Robot pâtissier","Stand Mixer"),("mixeur-plongeant","Mixeur plongeant","Hand Blender"),("machine-cafe","Machine à café","Coffee Machine"),("bouilloire","Bouilloire","Kettle"),("grille-pain","Grille-pain","Toaster"),("rice-cooker","Cuiseur à riz","Rice Cooker"),("yaourtiere","Yaourtière","Yogurt Maker"),("extracteur-jus","Extracteur de jus","Juicer")],
"ustensiles-accessoires":[("couteau-chef","Couteau de chef","Chef Knife"),("spatule","Spatule","Spatula"),("fouet","Fouet","Whisk"),("pince-cuisine","Pince cuisine","Kitchen Tongs"),("râpe","Râpe","Grater"),("passoire","Passoire","Colander"),("tamis","Tamis","Sieve"),("balance-cuisine","Balance cuisine","Kitchen Scale"),("thermometre-cuisine","Thermomètre cuisine","Kitchen Thermometer"),("boite-hermetique","Boîte hermétique","Food Container")],
"epicerie-fine-terroir":[("huile-olive","Huile d’olive","Olive Oil"),("vinaigre-balsamique","Vinaigre balsamique","Balsamic Vinegar"),("foie-gras","Foie gras","Foie Gras"),("terrine","Terrine","Pâté"),("miel-artisanal","Miel artisanal","Artisanal Honey"),("confiture-artisanale","Confiture artisanale","Artisanal Jam"),("fromage-affine","Fromage affiné","Aged Cheese"),("saucisson","Saucisson","Dry Sausage"),("biscuits-fins","Biscuits fins","Gourmet Biscuits"),("panier-garni","Panier garni","Gift Hamper")],
"the-cafe-infusions":[("cafe-grain","Café en grain","Coffee Beans"),("cafe-moulu","Café moulu","Ground Coffee"),("capsules-cafe","Capsules café","Coffee Pods"),("the-vert","Thé vert","Green Tea"),("the-noir","Thé noir","Black Tea"),("infusion-detox","Infusion détox","Detox Herbal Tea"),("matcha","Matcha","Matcha"),("mug-isotherme","Mug isotherme","Travel Mug"),("mousseur-lait","Mousseur à lait","Milk Frother"),("theiere","Théière","Teapot")],
"vins-spiritueux":[("vin-rouge","Vin rouge","Red Wine"),("vin-blanc","Vin blanc","White Wine"),("champagne","Champagne","Champagne"),("whisky","Whisky","Whisky"),("rhum","Rhum","Rum"),("gin","Gin","Gin"),("carafe-a-decanter","Carafe à décanter","Decanter"),("verres-a-vin","Verres à vin","Wine Glasses")],
"alimentation-bio":[("pates-bio","Pâtes bio","Organic Pasta"),("riz-bio","Riz bio","Organic Rice"),("granola-bio","Granola bio","Organic Granola"),("farine-bio","Farine bio","Organic Flour"),("huile-coco-bio","Huile coco bio","Organic Coconut Oil"),("beurre-cacahuete-bio","Beurre de cacahuète bio","Organic Peanut Butter"),("legumineuses-bio","Légumineuses bio","Organic Legumes"),("biscuits-bio","Biscuits bio","Organic Biscuits")],
"epices-condiments":[("poivre","Poivre","Pepper"),("sel-fin","Sel fin","Fine Salt"),("paprika","Paprika","Paprika"),("curcuma","Curcuma","Turmeric"),("curry","Curry","Curry"),("cannelle","Cannelle","Cinnamon"),("moutarde","Moutarde","Mustard"),("mayonnaise","Mayonnaise","Mayonnaise"),("sauce-soja","Sauce soja","Soy Sauce"),("pesto","Pesto","Pesto")],
"chocolat-confiserie":[("tablette-chocolat","Tablette chocolat","Chocolate Bar"),("truffes","Truffes","Chocolate Truffles"),("pate-a-tartiner","Pâte à tartiner","Chocolate Spread"),("bonbons","Bonbons","Candy"),("caramels","Caramels","Caramels"),("guimauves","Guimauves","Marshmallows"),("coffret-chocolat","Coffret chocolat","Chocolate Box"),("nougat","Nougat","Nougat")],
"livres-de-cuisine":[("livre-patisserie","Livre pâtisserie","Baking Cookbook"),("livre-cuisine-saine","Livre cuisine saine","Healthy Cookbook"),("livre-recettes-rapides","Livre recettes rapides","Quick Recipes Book"),("livre-vegan","Livre vegan","Vegan Cookbook"),("livre-barbecue","Livre barbecue","BBQ Cookbook"),("livre-cuisine-italienne","Livre cuisine italienne","Italian Cookbook")],
"meal-prep-lunch-box":[("lunch-box","Lunch box","Lunch Box"),("bento","Bento","Bento Box"),("sac-isotherme","Sac isotherme","Insulated Lunch Bag"),("bouteille-isotherme","Bouteille isotherme","Insulated Bottle"),("boites-repas-verre","Boîtes repas verre","Glass Meal Prep Containers"),("couverts-reutilisables","Couverts réutilisables","Reusable Cutlery"),("ice-pack","Pack de froid","Ice Pack"),("separateurs-repas","Séparateurs repas","Meal Dividers")],
# Health
"complements-alimentaires":[("omega-3","Oméga 3","Omega-3"),("collagene","Collagène","Collagen"),("probiotiques","Probiotiques","Probiotics"),("magnesium","Magnésium","Magnesium"),("vitamine-d","Vitamine D","Vitamin D"),("multivitamines","Multivitamines","Multivitamins"),("proteine-vegetale","Protéine végétale","Plant Protein"),("electrolytes","Électrolytes","Electrolytes")],
"vitamines-mineraux":[("vitamine-c","Vitamine C","Vitamin C"),("fer","Fer","Iron"),("zinc","Zinc","Zinc"),("calcium","Calcium","Calcium"),("selenium","Sélénium","Selenium"),("vitamine-b12","Vitamine B12","Vitamin B12"),("vitamine-k2","Vitamine K2","Vitamin K2"),("iode","Iode","Iodine")],
"phytotherapie-aromatherapie":[("huile-lavande","Huile essentielle de lavande","Lavender Essential Oil"),("huile-menthe-poivree","Huile essentielle de menthe poivrée","Peppermint Essential Oil"),("tisane-camomille","Tisane camomille","Chamomile Tea"),("gummies-plantes","Gummies plantes","Herbal Gummies"),("spray-oreiller","Spray oreiller","Pillow Spray"),("baume-plantes","Baume aux plantes","Herbal Balm"),("diffuseur-aroma","Diffuseur arôme","Aroma Diffuser"),("roll-on-huiles","Roll-on huiles","Essential Oil Roll-On")],
"medecines-douces":[("bouillotte","Bouillotte","Hot Water Bottle"),("patch-chauffant","Patch chauffant","Heat Patch"),("ceinture-lombaire","Ceinture lombaire","Back Support Belt"),("bracelet-acupression","Bracelet acupression","Acupressure Wristband"),("balles-massage","Balles massage","Massage Balls"),("oreiller-cervical","Oreiller cervical","Cervical Pillow"),("pistolet-massage","Pistolet de massage","Massage Gun"),("appareil-tens","Appareil TENS","TENS Device")],
"yoga-meditation":[("tapis-yoga","Tapis de yoga","Yoga Mat"),("briques-yoga","Briques de yoga","Yoga Blocks"),("sangle-yoga","Sangle de yoga","Yoga Strap"),("zafu","Zafu","Meditation Cushion"),("bol-chantant","Bol chantant","Singing Bowl"),("banc-meditation","Banc de méditation","Meditation Bench"),("roue-yoga","Roue de yoga","Yoga Wheel"),("couverture-yoga","Couverture yoga","Yoga Blanket")],
"sante-feminine":[("culotte-menstruelle","Culotte menstruelle","Period Underwear"),("cup-menstruelle","Cup menstruelle","Menstrual Cup"),("bouillotte-regles","Bouillotte règles","Period Heating Pad"),("lubrifiant","Lubrifiant","Lubricant"),("ovulation-test","Test d’ovulation","Ovulation Test"),("gel-intime","Gel intime","Intimate Wash"),("protege-slip-lavable","Protège-slip lavable","Reusable Panty Liner"),("supplement-cycle","Complément cycle","Cycle Support Supplement")],
"sante-intestinale":[("probiotiques-gut","Probiotiques intestin","Gut Probiotics"),("fibres-solubles","Fibres solubles","Soluble Fiber"),("kombucha","Kombucha","Kombucha"),("gingembre","Gingembre","Ginger"),("charbon-actif","Charbon actif","Activated Charcoal"),("enzyme-digestive","Enzyme digestive","Digestive Enzymes"),("tisane-digestion","Tisane digestion","Digestive Tea"),("complement-ballonnements","Complément ballonnements","Bloating Relief Supplement")],
"sommeil-relaxation":[("melatonine","Mélatonine","Melatonin"),("masque-nuit","Masque nuit","Sleep Mask"),("bruit-blanc","Machine bruit blanc","White Noise Machine"),("veilleuse-relax","Veilleuse relax","Relaxing Night Light"),("couverture-lestee","Couverture lestée","Weighted Blanket"),("spray-sommeil","Spray sommeil","Sleep Spray"),("infusion-sommeil","Infusion sommeil","Sleep Tea"),("oreiller-memoire","Oreiller mémoire","Memory Foam Pillow")],
"minceur-detox":[("the-detox","Thé détox","Detox Tea"),("gourde-infuseur","Gourde infuseur","Infuser Bottle"),("balance-impedancemetre","Balance impédancemètre","Smart Scale"),("substitut-repas","Substitut de repas","Meal Replacement"),("complement-brule-graisse","Complément brûle-graisse","Fat Burner"),("shaker","Shaker","Shaker Bottle"),("ceinture-sudation","Ceinture sudation","Sweat Belt"),("livre-recettes-light","Livre recettes light","Light Recipes Book")],
"hygiene-naturelle":[("savon-intime-naturel","Savon intime naturel","Natural Intimate Wash"),("deodorant-solide","Déodorant solide","Solid Deodorant"),("oriculi","Oriculi","Ear Cleaner Stick"),("cotons-lavables","Cotons lavables","Reusable Cotton Pads"),("papier-toilette-recycle","Papier toilette recyclé","Recycled Toilet Paper"),("brosse-dents-bambou","Brosse à dents bambou","Bamboo Toothbrush"),("rasoir-surete","Rasoir de sûreté","Safety Razor"),("shampoing-solide-hygiene","Shampoing solide","Solid Shampoo")],
# Sport
"equipement-fitness-maison":[("halteres","Haltères","Dumbbells"),("kettlebell","Kettlebell","Kettlebell"),("bande-resistance","Bande de résistance","Resistance Band"),("banc-musculation","Banc de musculation","Weight Bench"),("barre-traction","Barre de traction","Pull-Up Bar"),("corde-a-sauter","Corde à sauter","Jump Rope"),("velo-appartement","Vélo d’appartement","Exercise Bike"),("rameur","Rameur","Rowing Machine"),("tapis-course","Tapis de course","Treadmill"),("ab-wheel","Roue abdominale","Ab Wheel")],
"vetements-sport":[("t-shirt-sport","T-shirt sport","Sports T-Shirt"),("short-training","Short training","Training Shorts"),("legging-compression","Legging compression","Compression Leggings"),("veste-sport","Veste sport","Sports Jacket"),("chaussettes-sport","Chaussettes sport","Sports Socks"),("survetement","Survêtement","Tracksuit"),("debardeur-sport","Débardeur sport","Sports Tank"),("gants-musculation","Gants musculation","Weightlifting Gloves")],
"chaussures-sport":[("chaussures-running","Chaussures running","Running Shoes"),("chaussures-training","Chaussures training","Training Shoes"),("chaussures-randonnee","Chaussures randonnée","Hiking Shoes"),("chaussures-basket","Chaussures basket","Basketball Shoes"),("chaussures-foot","Chaussures foot","Football Boots"),("chaussures-tennis","Chaussures tennis","Tennis Shoes"),("sandales-rando","Sandales rando","Hiking Sandals"),("semelles-sport","Semelles sport","Sports Insoles")],
"nutrition-sportive":[("whey","Whey","Whey Protein"),("creatine","Créatine","Creatine"),("bcaa","BCAA","BCAA"),("pre-workout","Pre-workout","Pre-Workout"),("barres-proteinees","Barres protéinées","Protein Bars"),("gainer","Gainer","Mass Gainer"),("boisson-isotonique","Boisson isotonique","Isotonic Drink"),("electrolytes-sport","Électrolytes sport","Sports Electrolytes")],
"running-cardio":[("montre-running","Montre running","Running Watch"),("ceinture-cardio","Ceinture cardio","Heart Rate Belt"),("lampe-frontale-running","Lampe frontale running","Running Headlamp"),("ceinture-hydratation","Ceinture hydratation","Hydration Belt"),("brassard-telephone","Brassard téléphone","Phone Armband"),("chaussettes-running","Chaussettes running","Running Socks"),("gourde-running","Gourde running","Running Flask"),("ecouteurs-sport","Écouteurs sport","Sports Earbuds")],
"yoga-pilates":[("tapis-pilates","Tapis pilates","Pilates Mat"),("anneau-pilates","Anneau pilates","Pilates Ring"),("balle-pilates","Balle pilates","Pilates Ball"),("elastique-pilates","Élastique pilates","Pilates Band"),("chaussettes-antiderapantes","Chaussettes antidérapantes","Grip Socks"),("foam-roller","Foam roller","Foam Roller"),("serviette-yoga","Serviette yoga","Yoga Towel"),("tenue-yoga","Tenue yoga","Yoga Outfit")],
"sports-de-raquette":[("raquette-tennis","Raquette tennis","Tennis Racket"),("balles-tennis","Balles tennis","Tennis Balls"),("raquette-padel","Raquette padel","Padel Racket"),("balles-padel","Balles padel","Padel Balls"),("raquette-badminton","Raquette badminton","Badminton Racket"),("volants","Volants","Shuttlecocks"),("grip-raquette","Grip raquette","Racket Grip"),("sac-raquette","Sac raquette","Racket Bag")],
"sports-d-hiver":[("skis","Skis","Skis"),("chaussures-ski","Chaussures de ski","Ski Boots"),("batons-ski","Bâtons de ski","Ski Poles"),("casque-ski","Casque ski","Ski Helmet"),("masque-ski","Masque ski","Ski Goggles"),("gants-ski","Gants ski","Ski Gloves"),("snowboard","Snowboard","Snowboard"),("veste-ski","Veste ski","Ski Jacket")],
"randonnee-outdoor":[("sac-randonnee","Sac randonnée","Hiking Backpack"),("batons-randonnee","Bâtons randonnée","Trekking Poles"),("gourde-filtrante","Gourde filtrante","Filtered Bottle"),("veste-impermeable","Veste imperméable","Waterproof Jacket"),("chaussures-trek","Chaussures trek","Trekking Shoes"),("boussole","Boussole","Compass"),("lampe-frontale","Lampe frontale","Headlamp"),("jumelles","Jumelles","Binoculars")],
"natation-aquatique":[("maillot-natation","Maillot natation","Swimsuit"),("bonnet-bain","Bonnet de bain","Swim Cap"),("lunettes-natation","Lunettes natation","Swimming Goggles"),("planche-natation","Planche natation","Kickboard"),("palmes","Palmes","Fins"),("tuba","Tuba","Snorkel"),("serviette-microfibre","Serviette microfibre","Microfiber Towel"),("sac-etanche","Sac étanche","Dry Bag")],
# Kids
"puericulture-bebe":[("poussette","Poussette","Stroller"),("siege-auto","Siège auto","Car Seat"),("porte-bebe","Porte-bébé","Baby Carrier"),("table-a-langer","Table à langer","Changing Table"),("transat-bebe","Transat bébé","Baby Bouncer"),("babyphone","Babyphone","Baby Monitor"),("veilleuse-bebe","Veilleuse bébé","Baby Night Light"),("sterilisateur-biberons","Stérilisateur biberons","Bottle Sterilizer")],
"jouets-jeux":[("peluche","Peluche","Plush Toy"),("jeu-construction","Jeu de construction","Building Set"),("poupee","Poupée","Doll"),("voiture-telecommandee","Voiture télécommandée","RC Car"),("puzzle-enfant","Puzzle enfant","Kids Puzzle"),("jeu-societe-enfant","Jeu de société enfant","Kids Board Game"),("jouet-educatif","Jouet éducatif","Educational Toy"),("trottinette-enfant","Trottinette enfant","Kids Scooter")],
"vetements-enfant":[("manteau-enfant-vet","Manteau enfant","Kids Coat"),("pantalon-enfant-vet","Pantalon enfant","Kids Pants"),("robe-fille","Robe fille","Girls Dress"),("sweat-enfant","Sweat enfant","Kids Hoodie"),("chaussons-enfant","Chaussons enfant","Kids Slippers"),("pyjama-enfant-vet","Pyjama enfant","Kids Pajamas"),("t-shirt-enfant-vet","T-shirt enfant","Kids T-Shirt"),("bonnet-enfant-vet","Bonnet enfant","Kids Beanie")],
"livres-education":[("album-jeunesse","Album jeunesse","Picture Book"),("livre-coloriage","Livre de coloriage","Coloring Book"),("abecedaire","Abécédaire","Alphabet Book"),("jeu-montessori","Jeu Montessori","Montessori Toy"),("ardoise-magique","Ardoise magique","Magic Slate"),("flashcards","Cartes éducatives","Flashcards"),("livre-anglais-enfant","Livre anglais enfant","Kids English Book"),("globe-enfant","Globe enfant","Kids Globe")],
"anniversaires-fetes":[("ballons","Ballons","Balloons"),("guirlande-anniversaire","Guirlande anniversaire","Birthday Garland"),("vaisselle-jetable","Vaisselle jetable","Party Tableware"),("pinata","Piñata","Piñata"),("bougies-gateau","Bougies gâteau","Cake Candles"),("deguisement-enfant","Déguisement enfant","Kids Costume"),("sachets-cadeaux","Sachets cadeaux","Party Favor Bags"),("machine-bulles","Machine à bulles","Bubble Machine")],
"securite-enfant":[("barriere-securite","Barrière de sécurité","Safety Gate"),("protege-coins","Protège-coins","Corner Protectors"),("cache-prises","Cache-prises","Outlet Covers"),("verrou-placard","Verrou placard","Cabinet Lock"),("barriere-lit","Barrière de lit","Bed Rail"),("bracelet-identification","Bracelet identification","ID Bracelet"),("harnais-marche","Harnais marche","Walking Harness"),("camera-chambre","Caméra chambre","Nursery Camera")],
"activites-creatives":[("pate-a-modeler","Pâte à modeler","Modeling Clay"),("feutres","Feutres","Markers"),("peinture-doigts","Peinture doigts","Finger Paint"),("cahier-activites","Cahier activités","Activity Book"),("gommettes","Gommettes","Stickers"),("kit-bracelets","Kit bracelets","Bracelet Kit"),("origami-enfant","Origami enfant","Kids Origami Kit"),("perles","Perles","Beads")],
"alimentation-bebe":[("biberon","Biberon","Baby Bottle"),("chaise-haute","Chaise haute","High Chair"),("robot-bebe","Robot bébé","Baby Food Maker"),("cuillere-silicone","Cuillère silicone","Silicone Spoon"),("assiette-ventouse","Assiette ventouse","Suction Plate"),("gobelet-anti-fuite","Gobelet anti-fuite","Sippy Cup"),("petits-pots","Petits pots","Baby Jars"),("lait-infantile","Lait infantile","Infant Formula")],
"mobilier-chambre-enfant":[("lit-bebe","Lit bébé","Baby Crib"),("lit-evolutif","Lit évolutif","Convertible Bed"),("armoire-enfant","Armoire enfant","Kids Wardrobe"),("coffre-jouets","Coffre à jouets","Toy Chest"),("bureau-enfant","Bureau enfant","Kids Desk"),("chaise-enfant","Chaise enfant","Kids Chair"),("etagere-livres","Étagère livres","Book Shelf"),("tapis-enfant","Tapis enfant","Kids Rug")],
"fournitures-scolaires":[("cartable","Cartable","School Bag"),("trousse","Trousse","Pencil Case"),("stylos","Stylos","Pens"),("crayons-couleur","Crayons de couleur","Colored Pencils"),("agenda-scolaire","Agenda scolaire","School Planner"),("classeur","Classeur","Binder"),("gourde-ecole","Gourde école","School Water Bottle"),("calculatrice","Calculatrice","Calculator")],
# Pets
"alimentation-chien":[("croquettes-chien","Croquettes chien","Dog Kibble"),("patee-chien","Pâtée chien","Dog Wet Food"),("friandises-chien","Friandises chien","Dog Treats"),("os-a-macher","Os à mâcher","Chew Bone"),("complement-articulations-chien","Complément articulations chien","Dog Joint Supplement"),("lait-chiot","Lait chiot","Puppy Milk"),("gamelle-anti-glouton","Gamelle anti-glouton","Slow Feeder"),("fontaine-eau-chien","Fontaine à eau chien","Dog Water Fountain")],
"alimentation-chat":[("croquettes-chat","Croquettes chat","Cat Kibble"),("patee-chat","Pâtée chat","Cat Wet Food"),("friandises-chat","Friandises chat","Cat Treats"),("herbe-a-chat","Herbe à chat","Cat Grass"),("lait-chat","Lait chat","Cat Milk"),("fontaine-eau-chat","Fontaine à eau chat","Cat Water Fountain"),("gamelle-chat","Gamelle chat","Cat Bowl"),("supplement-boules-poils","Complément boules de poils","Hairball Supplement")],
"accessoires-chien":[("laisse","Laisse","Leash"),("harnais-chien","Harnais chien","Dog Harness"),("collier-chien","Collier chien","Dog Collar"),("medaille","Médaille","Pet Tag"),("panier-chien","Panier chien","Dog Bed"),("manteau-chien","Manteau chien","Dog Coat"),("cage-transport-chien","Cage transport chien","Dog Carrier"),("sac-crottes","Sacs à crottes","Poop Bags")],
"accessoires-chat":[("arbre-a-chat","Arbre à chat","Cat Tree"),("litiere","Litière","Cat Litter"),("bac-a-litiere","Bac à litière","Litter Box"),("griffoir","Griffoir","Scratching Post"),("panier-chat","Panier chat","Cat Bed"),("caisse-transport-chat","Caisse transport chat","Cat Carrier"),("collier-chat","Collier chat","Cat Collar"),("hamac-fenetre-chat","Hamac fenêtre chat","Cat Window Hammock")],
"soins-hygiene-animaux":[("shampoing-animal","Shampoing animal","Pet Shampoo"),("brosse-animal","Brosse animal","Pet Brush"),("coupe-griffes","Coupe-griffes","Nail Clippers"),("lingettes-animal","Lingettes animal","Pet Wipes"),("spray-antiparasitaire","Spray antiparasitaire","Anti-Parasite Spray"),("dentifrice-animal","Dentifrice animal","Pet Toothpaste"),("soin-oreilles-animal","Soin oreilles animal","Pet Ear Cleaner"),("serviette-sechage-animal","Serviette séchage animal","Pet Drying Towel")],
"jouets-pour-animaux":[("balle-chien","Balle chien","Dog Ball"),("corde-chien","Corde chien","Dog Rope Toy"),("jouet-couineur","Jouet couineur","Squeaky Toy"),("laser-chat","Laser chat","Cat Laser Toy"),("souris-chat","Souris chat","Cat Mouse Toy"),("circuit-balles-chat","Circuit balles chat","Cat Ball Track"),("tapis-fouille","Tapis de fouille","Snuffle Mat"),("frisbee-chien","Frisbee chien","Dog Frisbee")],
"aquariophilie":[("aquarium","Aquarium","Aquarium"),("filtre-aquarium","Filtre aquarium","Aquarium Filter"),("chauffage-aquarium","Chauffage aquarium","Aquarium Heater"),("pompe-air","Pompe à air","Air Pump"),("gravier-aquarium","Gravier aquarium","Aquarium Gravel"),("plante-aquatique","Plante aquatique","Aquatic Plant"),("nourriture-poissons","Nourriture poissons","Fish Food"),("epuisette","Épuisette","Fish Net")],
"rongeurs-lapins":[("cage-rongeur","Cage rongeur","Rodent Cage"),("foin","Foin","Hay"),("litiere-rongeur","Litière rongeur","Rodent Bedding"),("roue-hamster","Roue hamster","Hamster Wheel"),("biberon-rongeur","Biberon rongeur","Rodent Water Bottle"),("maison-lapin","Maison lapin","Rabbit House"),("jouet-ronger","Jouet à ronger","Chew Toy"),("granules-lapin","Granulés lapin","Rabbit Pellets")],
"sante-animale":[("vermifuge","Vermifuge","Dewormer"),("antipuce","Antipuce","Flea Treatment"),("complement-peau-pelage","Complément peau pelage","Skin & Coat Supplement"),("spray-cicatrisant","Spray cicatrisant","Healing Spray"),("probiotiques-animaux","Probiotiques animaux","Pet Probiotics"),("calmant-animal","Calmant animal","Pet Calming Aid"),("trousse-secours-animal","Trousse secours animal","Pet First Aid Kit"),("anti-tiques","Anti-tiques","Tick Treatment")],
"elevage-reproduction":[("incubateur","Incubateur","Incubator"),("couveuse","Couveuse","Brooder"),("marqueur-elevage","Marqueur élevage","Livestock Marker"),("nidification","Matériel nidification","Nesting Material"),("lampe-chauffante","Lampe chauffante","Heat Lamp"),("abreuvoir","Abreuvoir","Water Dispenser"),("mangeoire","Mangeoire","Feeder"),("balance-animale","Balance animale","Animal Scale")],
# Garden
"mobilier-de-jardin":[("table-jardin","Table de jardin","Garden Table"),("chaise-jardin","Chaise de jardin","Garden Chair"),("salon-jardin","Salon de jardin","Patio Set"),("transat","Transat","Sun Lounger"),("parasol","Parasol","Sun Umbrella"),("coffre-exterieur","Coffre extérieur","Outdoor Storage Box"),("hamac","Hamac","Hammock"),("banc-jardin","Banc jardin","Garden Bench")],
"outillage-jardinage":[("pelle","Pelle","Shovel"),("râteau","Râteau","Rake"),("sécateur","Sécateur","Pruning Shears"),("gants-jardin","Gants jardin","Gardening Gloves"),("tondeuse","Tondeuse","Lawn Mower"),("debroussailleuse","Débroussailleuse","Brush Cutter"),("souffleur","Souffleur","Leaf Blower"),("brouette","Brouette","Wheelbarrow")],
"plantes-fleurs":[("plante-interieure","Plante intérieure","Indoor Plant"),("plante-exterieure","Plante extérieure","Outdoor Plant"),("orchidee","Orchidée","Orchid"),("rosier","Rosier","Rose Bush"),("lavande-plante","Lavande","Lavender Plant"),("bulbes-fleurs","Bulbes fleurs","Flower Bulbs"),("terreau","Terreau","Potting Soil"),("pot-fleurs","Pot de fleurs","Flower Pot")],
"potager-semences":[("graines-tomates","Graines tomates","Tomato Seeds"),("graines-salades","Graines salades","Lettuce Seeds"),("mini-serre","Mini-serre","Mini Greenhouse"),("carre-potager","Carré potager","Raised Garden Bed"),("composteur","Composteur","Composter"),("engrais-potager","Engrais potager","Vegetable Fertilizer"),("arceau-potager","Arceau potager","Garden Hoops"),("etiquettes-plantes","Étiquettes plantes","Plant Labels")],
"piscine-spa":[("spa-gonflable","Spa gonflable","Inflatable Spa"),("piscine-hors-sol","Piscine hors-sol","Above-Ground Pool"),("pompe-piscine","Pompe piscine","Pool Pump"),("bache-piscine","Bâche piscine","Pool Cover"),("epuisette-piscine","Épuisette piscine","Pool Net"),("robot-piscine","Robot piscine","Pool Cleaner"),("testeur-ph","Testeur pH","pH Tester"),("marche-piscine","Marche piscine","Pool Steps")],
"barbecue-plancha":[("barbecue-charbon","Barbecue charbon","Charcoal BBQ"),("barbecue-gaz","Barbecue gaz","Gas BBQ"),("plancha","Plancha","Plancha Grill"),("ustensiles-bbq","Ustensiles BBQ","BBQ Tools"),("housse-barbecue","Housse barbecue","BBQ Cover"),("thermometre-viande","Thermomètre viande","Meat Thermometer"),("grille-barbecue","Grille barbecue","BBQ Grill Rack"),("fumoir","Fumoir","Smoker")],
"eclairage-exterieur":[("guirlande-solaire","Guirlande solaire","Solar String Lights"),("borne-solaire","Borne solaire","Solar Path Light"),("projecteur-led","Projecteur LED","LED Floodlight"),("lanterne-exterieure","Lanterne extérieure","Outdoor Lantern"),("applique-exterieure","Applique extérieure","Outdoor Wall Light"),("balise-jardin","Balise jardin","Garden Bollard Light"),("detecteur-mouvement","Détecteur mouvement","Motion Sensor Light"),("lampe-nomade","Lampe nomade","Portable Outdoor Lamp")],
"abris-pergolas":[("pergola","Pergola","Pergola"),("abri-jardin","Abri jardin","Garden Shed"),("tonnelle","Tonnelle","Gazebo"),("voile-ombrage","Voile d’ombrage","Shade Sail"),("serre-jardin","Serre jardin","Garden Greenhouse"),("coffre-outils-exterieur","Coffre outils extérieur","Outdoor Tool Chest"),("garage-velo","Garage vélo","Bike Shed"),("abri-buches","Abri bûches","Log Store")],
"arrosage":[("tuyau-arrosage","Tuyau d’arrosage","Garden Hose"),("devidoir","Dévidoir","Hose Reel"),("arroseur","Arroseur","Sprinkler"),("goutte-a-goutte","Goutte-à-goutte","Drip Irrigation Kit"),("programmateur","Programmateur","Water Timer"),("recuperateur-eau","Récupérateur d’eau","Rain Barrel"),("pistolet-arrosage","Pistolet arrosage","Spray Gun"),("arrosoir","Arrosoir","Watering Can")],
"decoration-exterieure":[("nain-jardin","Nain de jardin","Garden Gnome"),("fontaine-jardin","Fontaine jardin","Garden Fountain"),("statue-exterieure","Statue extérieure","Outdoor Statue"),("tapis-exterieur","Tapis extérieur","Outdoor Rug"),("coussin-exterieur","Coussin extérieur","Outdoor Cushion"),("boite-aux-lettres","Boîte aux lettres","Mailbox"),("thermometre-exterieur","Thermomètre extérieur","Outdoor Thermometer"),("carillon","Carillon","Wind Chime")],
# Tech
"smartphones-accessoires":[("smartphone","Smartphone","Smartphone"),("coque-telephone","Coque téléphone","Phone Case"),("verre-trempe","Verre trempé","Tempered Glass"),("chargeur-rapide","Chargeur rapide","Fast Charger"),("cable-usb-c","Câble USB-C","USB-C Cable"),("support-telephone-voiture","Support téléphone voiture","Car Phone Mount"),("batterie-externe","Batterie externe","Power Bank"),("ring-light-smartphone","Ring light smartphone","Phone Ring Light"),("trépied-smartphone","Trépied smartphone","Phone Tripod"),("objectif-smartphone","Objectif smartphone","Phone Lens")],
"audio":[("casque-audio","Casque audio","Headphones"),("ecouteurs-sans-fil","Écouteurs sans fil","Wireless Earbuds"),("enceinte-bluetooth","Enceinte Bluetooth","Bluetooth Speaker"),("barre-de-son","Barre de son","Soundbar"),("micro-usb","Micro USB","USB Microphone"),("platine-vinyle","Platine vinyle","Turntable"),("radio-reveil","Radio-réveil","Clock Radio"),("dac-audio","DAC audio","Audio DAC")],
"maison-connectee":[("ampoule-connectee","Ampoule connectée","Smart Bulb"),("prise-connectee","Prise connectée","Smart Plug"),("camera-surveillance","Caméra surveillance","Security Camera"),("thermostat-connecte","Thermostat connecté","Smart Thermostat"),("assistant-vocal","Assistant vocal","Smart Speaker"),("serrure-connectee","Serrure connectée","Smart Lock"),("detecteur-fumee-connecte","Détecteur fumée connecté","Smart Smoke Detector"),("visiophone-connecte","Visiophone connecté","Smart Doorbell")],
"wearables-montres":[("montre-connectee","Montre connectée","Smartwatch"),("bracelet-connecte","Bracelet connecté","Fitness Tracker"),("balance-connectee","Balance connectée","Smart Scale"),("bague-connectee","Bague connectée","Smart Ring"),("casque-vr","Casque VR","VR Headset"),("lunettes-connectees","Lunettes connectées","Smart Glasses"),("gps-sport","GPS sport","Sports GPS"),("capteur-sommeil","Capteur sommeil","Sleep Tracker")],
"photo-video":[("appareil-photo","Appareil photo","Camera"),("objectif-photo","Objectif photo","Camera Lens"),("trepied","Trépied","Tripod"),("gimbal","Gimbal","Gimbal"),("camera-action","Caméra action","Action Camera"),("micro-camera","Micro caméra","Camera Microphone"),("ring-light","Ring light","Ring Light"),("carte-memoire","Carte mémoire","Memory Card")],
"tablettes-pc":[("ordinateur-portable","Ordinateur portable","Laptop"),("pc-fixe","PC fixe","Desktop PC"),("tablette","Tablette","Tablet"),("ecran-pc","Écran PC","Monitor"),("clavier","Clavier","Keyboard"),("souris","Souris","Mouse"),("hub-usb","Hub USB","USB Hub"),("ssd-externe","SSD externe","External SSD")],
"gaming":[("console","Console","Game Console"),("manette","Manette","Controller"),("chaise-gaming","Chaise gaming","Gaming Chair"),("casque-gaming","Casque gaming","Gaming Headset"),("clavier-gaming","Clavier gaming","Gaming Keyboard"),("souris-gaming","Souris gaming","Gaming Mouse"),("tapis-souris","Tapis de souris","Mouse Pad"),("ecran-gaming","Écran gaming","Gaming Monitor")],
"accessoires-bureau":[("support-ordinateur","Support ordinateur","Laptop Stand"),("lampe-bureau-led","Lampe bureau LED","LED Desk Lamp"),("organiseur-bureau","Organiseur bureau","Desk Organizer"),("siege-ergonomique","Siège ergonomique","Ergonomic Chair"),("repose-poignets","Repose-poignets","Wrist Rest"),("station-accueil","Station d’accueil","Docking Station"),("webcam","Webcam","Webcam"),("micro-casque","Micro-casque","Headset")],
"chargeurs-batteries":[("chargeur-secteur","Chargeur secteur","Wall Charger"),("chargeur-sans-fil","Chargeur sans fil","Wireless Charger"),("station-charge","Station de charge","Charging Station"),("pile-rechargeable","Pile rechargeable","Rechargeable Battery"),("chargeur-piles","Chargeur piles","Battery Charger"),("onduleur","Onduleur","UPS"),("batterie-appareil-photo","Batterie appareil photo","Camera Battery"),("cable-lightning","Câble Lightning","Lightning Cable")],
"impression-3d-domotique":[("imprimante-3d","Imprimante 3D","3D Printer"),("filament-pla","Filament PLA","PLA Filament"),("resine-impression","Résine impression","3D Printer Resin"),("stylo-3d","Stylo 3D","3D Pen"),("capteur-domotique","Capteur domotique","Home Sensor"),("box-domotique","Box domotique","Smart Home Hub"),("relais-connecte","Relais connecté","Smart Relay"),("module-zigbee","Module Zigbee","Zigbee Module")],
# Travel leisure
"bagages-valises":[("valise-cabine","Valise cabine","Carry-On Suitcase"),("valise-soute","Valise soute","Checked Suitcase"),("sac-weekend","Sac week-end","Weekend Bag"),("valise-rigide","Valise rigide","Hard Shell Suitcase"),("organisateur-valise","Organisateur valise","Packing Cubes"),("etiquette-bagage","Étiquette bagage","Luggage Tag"),("pese-bagage","Pèse-bagage","Luggage Scale"),("housse-valise","Housse valise","Suitcase Cover")],
"accessoires-voyage":[("oreiller-voyage","Oreiller voyage","Travel Pillow"),("masque-avion","Masque avion","Travel Eye Mask"),("adaptateur-universel","Adaptateur universel","Universal Adapter"),("trousse-voyage","Trousse voyage","Travel Pouch"),("flacons-cabine","Flacons cabine","Travel Bottles"),("porte-passeport","Porte-passeport","Passport Holder"),("cadeau-voyage","Cadenas voyage","Travel Lock"),("couverture-voyage","Couverture voyage","Travel Blanket")],
"livres-lecture":[("roman","Roman","Novel"),("manga","Manga","Manga"),("liseuse","Liseuse","E-Reader"),("lampe-lecture","Lampe lecture","Reading Light"),("marque-page","Marque-page","Bookmark"),("livre-poche","Livre de poche","Paperback"),("etagere-livres-loisir","Étagère livres","Bookcase"),("journal-lecture","Journal de lecture","Reading Journal")],
"jeux-de-societe":[("jeu-strategie","Jeu de stratégie","Strategy Board Game"),("jeu-ambiance","Jeu d’ambiance","Party Game"),("jeu-cooperatif","Jeu coopératif","Cooperative Board Game"),("jeu-cartes","Jeu de cartes","Card Game"),("jeu-famille","Jeu famille","Family Board Game"),("jeu-enquete","Jeu enquête","Mystery Game"),("poker-set","Set poker","Poker Set"),("accessoires-jeu","Accessoires jeu","Game Accessories")],
"loisirs-creatifs":[("machine-couture","Machine à coudre","Sewing Machine"),("canevas","Canevas","Needlepoint Kit"),("aquarelle","Aquarelle","Watercolor Set"),("tricot-kit","Kit tricot","Knitting Kit"),("broderie-kit","Kit broderie","Embroidery Kit"),("argile-auto-durcissante","Argile auto-durcissante","Air Dry Clay"),("scrapbooking","Scrapbooking","Scrapbooking Kit"),("calligraphie-kit","Kit calligraphie","Calligraphy Set")],
"photographie":[("appareil-instantane","Appareil instantané","Instant Camera"),("album-photo","Album photo","Photo Album"),("imprimante-photo","Imprimante photo","Photo Printer"),("sac-photo","Sac photo","Camera Bag"),("trépied-photo","Trépied photo","Photo Tripod"),("fond-photo","Fond photo","Photo Backdrop"),("reflecteur","Réflecteur","Reflector"),("telecommande-photo","Télécommande photo","Camera Remote")],
"camping-bivouac":[("tente","Tente","Tent"),("sac-couchage","Sac de couchage","Sleeping Bag"),("matelas-camping","Matelas camping","Camping Mattress"),("rechaud","Réchaud","Camping Stove"),("lampe-camping","Lampe camping","Camping Lantern"),("chaise-pliante","Chaise pliante","Folding Chair"),("table-pliante","Table pliante","Folding Table"),("popote","Popote","Cook Set")],
"musique-instruments":[("guitare","Guitare","Guitar"),("piano-numerique","Piano numérique","Digital Piano"),("ukulele","Ukulélé","Ukulele"),("micro-studio","Micro studio","Studio Microphone"),("carte-son","Carte son","Audio Interface"),("pupitre","Pupitre","Music Stand"),("casque-studio","Casque studio","Studio Headphones"),("pedale-guitare","Pédale guitare","Guitar Pedal")],
"jeux-video":[("jeu-ps5","Jeu PS5","PS5 Game"),("jeu-switch","Jeu Switch","Switch Game"),("jeu-pc","Jeu PC","PC Game"),("volant-simulation","Volant simulation","Racing Wheel"),("manette-supplementaire","Manette supplémentaire","Extra Controller"),("carte-cadeau-gaming","Carte cadeau gaming","Gaming Gift Card"),("support-console","Support console","Console Stand"),("capture-card","Carte d’acquisition","Capture Card")],
"puzzles-collections":[("puzzle-1000","Puzzle 1000 pièces","1000-Piece Puzzle"),("puzzle-3d","Puzzle 3D","3D Puzzle"),("figurine-collection","Figurine collection","Collectible Figure"),("album-cartes","Album cartes","Trading Card Binder"),("protection-cartes","Protection cartes","Card Sleeves"),("display-figurines","Display figurines","Display Case"),("maquette","Maquette","Model Kit"),("collector-box","Boîte collector","Collector Box")],
# Senior
"mobilite-aide-marche":[("canne","Canne","Walking Cane"),("deambulateur","Déambulateur","Walker"),("rollator","Rollator","Rollator"),("fauteuil-roulant","Fauteuil roulant","Wheelchair"),("barre-appui","Barre d’appui","Grab Bar"),("rehausseur-wc","Rehausseur WC","Raised Toilet Seat"),("rampe-seuil","Rampe de seuil","Threshold Ramp"),("chaussures-orthopediques","Chaussures orthopédiques","Orthopedic Shoes")],
"confort-bien-etre":[("coussin-lombaire","Coussin lombaire","Lumbar Cushion"),("fauteuil-releveur","Fauteuil releveur","Lift Chair"),("plaid-chauffant","Plaid chauffant","Heated Throw"),("chauffe-pieds","Chauffe-pieds","Foot Warmer"),("oreiller-ergonomique","Oreiller ergonomique","Ergonomic Pillow"),("matelas-anti-escarres","Matelas anti-escarres","Pressure Relief Mattress"),("fauteuil-massage","Fauteuil massage","Massage Chair"),("ouvre-bocal","Ouvre-bocal","Jar Opener")],
"sante-medicaments":[("pilulier","Pilulier","Pill Organizer"),("tensiometre","Tensiomètre","Blood Pressure Monitor"),("oxymetre","Oxymètre","Pulse Oximeter"),("thermometre","Thermomètre","Thermometer"),("glucometre","Glucomètre","Blood Glucose Meter"),("nebuliseur","Nébuliseur","Nebulizer"),("genouillere","Genouillère","Knee Brace"),("bas-contention","Bas de contention","Compression Stockings")],
"loisirs-senior":[("mots-fleches","Mots fléchés","Crossword Book"),("tricot","Tricot","Knitting Set"),("puzzle-senior","Puzzle senior","Large Piece Puzzle"),("livre-gros-caracteres","Livre gros caractères","Large Print Book"),("radio-portable","Radio portable","Portable Radio"),("jeu-memoire","Jeu mémoire","Memory Game"),("coloriage-adulte","Coloriage adulte","Adult Coloring Book"),("tablette-simplifiee","Tablette simplifiée","Simplified Tablet")],
"maison-adaptee":[("detecteur-chute","Détecteur chute","Fall Detector"),("teleassistance","Téléassistance","Medical Alert System"),("eclairage-automatique","Éclairage automatique","Automatic Night Light"),("ouvre-porte-electrique","Ouvre-porte électrique","Automatic Door Opener"),("poignee-ergonomique","Poignée ergonomique","Ergonomic Handle"),("chaise-douche","Chaise douche","Shower Chair"),("marchepied-securise","Marchepied sécurisé","Safe Step Stool"),("revetement-antiderapant","Revêtement antidérapant","Anti-Slip Mat")],
"audition-optique":[("appareil-auditif","Appareil auditif","Hearing Aid"),("amplificateur-son","Amplificateur son","Personal Sound Amplifier"),("lunettes-loupe","Lunettes loupe","Magnifying Glasses"),("lampe-loupe","Lampe loupe","Magnifying Lamp"),("telephone-grosses-touches","Téléphone grosses touches","Big Button Phone"),("reveil-vibrant","Réveil vibrant","Vibrating Alarm Clock"),("loupe-lecture","Loupe lecture","Reading Magnifier"),("nettoyant-aide-auditive","Nettoyant aide auditive","Hearing Aid Cleaner")],
"numerique-senior":[("tablette-senior","Tablette senior","Senior Tablet"),("telephone-simple","Téléphone simple","Easy Cell Phone"),("ordinateur-tout-en-un","Ordinateur tout-en-un","All-in-One Computer"),("souris-ergonomique","Souris ergonomique","Ergonomic Mouse"),("clavier-grosses-touches","Clavier grosses touches","Large Key Keyboard"),("assistant-vocal-senior","Assistant vocal senior","Voice Assistant"),("cadre-photo-numerique","Cadre photo numérique","Digital Photo Frame"),("montre-sos","Montre SOS","SOS Watch")],
"voyage-senior":[("valise-legere","Valise légère","Lightweight Suitcase"),("oreiller-cervical-voyage","Oreiller cervical voyage","Travel Neck Pillow"),("canne-pliante","Canne pliante","Foldable Cane"),("pilulier-voyage","Pilulier voyage","Travel Pill Organizer"),("organisateur-documents","Organisateur documents","Travel Document Organizer"),("ceinture-securite-voyage","Ceinture sécurité voyage","Travel Money Belt"),("sac-roulettes","Sac à roulettes","Rolling Bag"),("assurance-voyage-guide","Guide assurance voyage","Travel Insurance Guide")],
"garde-robe-confort":[("chaussures-confort","Chaussures confort","Comfort Shoes"),("gilet-chaud","Gilet chaud","Warm Cardigan"),("pantalon-elastique","Pantalon élastique","Elastic Waist Pants"),("chemise-facile","Chemise facile","Easy Closure Shirt"),("chaussons-antiderapants","Chaussons antidérapants","Non-Slip Slippers"),("soutien-lombaire-textile","Soutien lombaire textile","Support Belt"),("veste-legere","Veste légère","Light Jacket"),("pyjama-confort","Pyjama confort","Comfort Pajamas")],
"jardinage-senior":[("tabouret-jardinage","Tabouret jardinage","Gardening Stool"),("outils-manches-longs","Outils manches longs","Long-Handle Tools"),("genouillere-jardin","Genouillère jardin","Garden Kneeler"),("arrosoir-leger","Arrosoir léger","Lightweight Watering Can"),("gants-jardin-senior","Gants jardin senior","Senior Gardening Gloves"),("sac-dechets-jardin","Sac déchets jardin","Garden Waste Bag"),("pulverisateur-leger","Pulvérisateur léger","Light Sprayer"),("bac-potager-haut","Bac potager haut","Raised Planter")],
# DIY
"outillage-electroportatif":[("perceuse-visseuse","Perceuse visseuse","Drill Driver"),("visseuse-impact","Visseuse à impact","Impact Driver"),("meuleuse","Meuleuse","Angle Grinder"),("ponceuse","Ponceuse","Sander"),("scie-sauteuse","Scie sauteuse","Jigsaw"),("scie-circulaire","Scie circulaire","Circular Saw"),("multitool","Outil multifonction","Oscillating Tool"),("batterie-outil","Batterie outil","Tool Battery")],
"peinture-enduits":[("peinture-acrylique","Peinture acrylique","Acrylic Paint"),("enduit-lissage","Enduit de lissage","Smoothing Compound"),("rouleau-pro","Rouleau pro","Professional Roller"),("bac-peinture","Bac peinture","Paint Tray"),("bache-protection","Bâche protection","Drop Cloth"),("ponceuse-mur","Ponceuse mur","Wall Sander"),("sous-couche-peinture","Sous-couche","Primer"),("spatule-enduit","Spatule enduit","Putty Knife")],
"plomberie":[("robinet","Robinet","Faucet"),("flexible-douche","Flexible douche","Shower Hose"),("joint-plomberie","Joint plomberie","Plumbing Washer"),("cle-plomberie","Clé plomberie","Pipe Wrench"),("deboucheur","Déboucheur","Drain Opener"),("siphon","Siphon","Trap"),("raccord-pvc","Raccord PVC","PVC Fitting"),("ruban-teflon","Ruban téflon","PTFE Tape")],
"electricite":[("prise-murale","Prise murale","Wall Socket"),("interrupteur","Interrupteur","Light Switch"),("ampoule-led","Ampoule LED","LED Bulb"),("disjoncteur","Disjoncteur","Circuit Breaker"),("rallonge","Rallonge","Extension Cord"),("multiprise","Multiprise","Power Strip"),("testeur-tension","Testeur tension","Voltage Tester"),("gaine-electrique","Gaine électrique","Electrical Conduit")],
"quincaillerie":[("vis","Vis","Screws"),("clous","Clous","Nails"),("chevilles","Chevilles","Wall Plugs"),("charniere","Charnière","Hinge"),("poignee-porte","Poignée de porte","Door Handle"),("serrure","Serrure","Lock"),("crochet","Crochet","Hook"),("boulons","Boulons","Bolts")],
"materiaux-construction":[("placo","Plaque de plâtre","Drywall"),("laine-verre","Laine de verre","Glass Wool"),("ciment","Ciment","Cement"),("mortier","Mortier","Mortar"),("bois-charpente","Bois charpente","Structural Timber"),("parpaing","Parpaing","Concrete Block"),("carrelage","Carrelage","Tiles"),("colle-carrelage","Colle carrelage","Tile Adhesive")],
"deco-diy-creatif":[("papier-adhesif","Papier adhésif","Adhesive Film"),("pochoir","Pochoir","Stencil"),("peinture-bombe","Peinture bombe","Spray Paint"),("perles-diy","Perles DIY","Craft Beads"),("pistolet-colle","Pistolet à colle","Glue Gun"),("colle-chaude","Colle chaude","Hot Glue Sticks"),("corde-macrame","Corde macramé","Macrame Rope"),("boite-crea","Boîte créa","Craft Box")],
"isolation-energie":[("joint-fenetre","Joint fenêtre","Window Seal"),("mousse-isolante","Mousse isolante","Expanding Foam"),("film-isolant","Film isolant","Insulation Film"),("thermostat-programmable","Thermostat programmable","Programmable Thermostat"),("boudin-porte","Boudin de porte","Door Draft Stopper"),("panneau-isolant","Panneau isolant","Insulation Panel"),("prise-programmable","Prise programmable","Timer Plug"),("reflecteur-radiateur","Réflecteur radiateur","Radiator Reflector")],
"menuiserie":[("rabot","Rabot","Plane"),("serre-joint","Serre-joint","Clamp"),("ponceuse-bois","Ponceuse bois","Wood Sander"),("mètre-ruban","Mètre ruban","Tape Measure"),("equerre","Équerre","Square"),("ciseau-bois","Ciseau bois","Wood Chisel"),("scie-a-main","Scie à main","Hand Saw"),("etabli","Établi","Workbench")],
"alarme-securite":[("alarme-maison","Alarme maison","Home Alarm"),("camera-ip","Caméra IP","IP Camera"),("detecteur-ouverture","Détecteur ouverture","Door Sensor"),("sirene","Sirène","Alarm Siren"),("coffre-fort","Coffre-fort","Safe"),("judas-numerique","Judas numérique","Digital Peephole"),("eclairage-securite","Éclairage sécurité","Security Light"),("serrure-connectee-secu","Serrure connectée","Smart Lock")],
}
# sanity missing count
all_niches=[]
for c in categories:
    for nid,nfr,nen in c["niches"]:
        all_niches.append(nid)
missing=[n for n in all_niches if n not in products_by_niche]
len(all_niches), len(products_by_niche), missing[:10]
